### ISSUE TITLE
Göra det mer attraktivt att slåss istället för att fly?

### ISSUE THREAD

**Issue by Itangalo** [Itangalo/flux#1]
I dagsläget (beta-3) måste en äventyrare backa ett steg om hon lyckas fly från en fiende. Mer än en speltestare har framfört att det vore bra att göra det mer lönsamt att välja att slåss istället för att fly. Några möjliga vägar framåt:

1. Ta bort möjligheten att fly, tillsammans med färdigheten Smyga. Detta skulle förenkla reglerna för strid, och även göra att äventyrare förlorar KP oftare än idag. Det skulle kanske också göra spelet mer platt.
2. Låt alla äventyrare som misslyckas med att fly förlora en KP. Gör det eventuellt också svårare att fly, så att man vanligtvis har mindre än 50 % chans att lyckas med att fly.
3. Ge någon bonus när man besegrar en fiende. Detta kan exempelvis vara att (a) få en fluxkristall, (b) få behålla vissa fiendekort och låta dem ge bonusar vid andra tillfällen i spelet, eller (c) behålla alla fiendekort och växla in dem när de blivit tillräckligt många/mäktiga eller när man kommer till något särskilt ställe.

Det bör sägas att äventyrare som backar ett steg när de flyr från fiender i princip förlorar ett drag, och på sikt löper tydligt större risk att Onda Trollkarlen ser dem. Men det är inte tydligt i de enskilda valen, och det är inte heller säkert att effekten är särskilt stark.

Frågan utreds närmare i [ett eget Google-dokument](https://docs.google.com/document/d/1glLKOerl_TNm7Go08XW3BpaGB2AdMy4eowp0cubDadE/edit?usp=sharing).

Slutsatsen i dokumentet är fem möjliga vägar:

1. Fortsätta som idag, men flyktvärdena ses över så att det inte är för enkelt att fly där det inte är meningen.
2. Ta bort fly och smyga helt.
3. Vunnen strid gör att spelaren får slå ett extra slag för en färdighet som använts, för att eventuellt få flux eller levla.
4. Bonus beskrivs på varje fiendekort, där de flesta bonusar innebär möjlighet att behålla kortet och cacha in vid tillfälle för att få bonusen.
5. En ny kortlek med småbonusar skapas som en expansion. Man får ett kort när fiender och andar besegrats. (Bonusarna är i princip samma som i alternativ 4.)

**Comment by Itangalo** [comment]
## Om alternativ 3: ge bonus när man besegrar fiende

En viktig mekanism i spelet är hur ofta Onda Trollkarlen ser dig (OTSD) dyker upp. Om spelare får behålla fiendekort kan OTSD bli betydligt vanligare, vilket då också kan göra spelet betydligt svårare. Det talar för att spelare *inte* ska behålla fiendekort. Å andra sidan, om spelare får *välja* att behålla fiendekort blir det istället ett val som introducerar lite mer djup och komplexitet i de val som redan finns. Är det värt att få bonusen, men få högre risk för OTSD?

Att ge fasta bonusar för vissa kort, så som "1 fluxkristall om du vinner" eller "offra kortet för att byta en trea mot en fyra" är lite lockande. En svårighet är att få plats med texten på korten, men det är en annan femma.

**Comment by Itangalo** [comment]
## Om alternativ 1: ta bort fly och smyga

En ständig jakt är att göra spelet mindre komplext. Att ta bort Fly och Smyga skulle minska komplexiteten, och är kanske den enda tydliga minskning av komplexitet som kvarstår att göra/testa.

Ändringen skulle göra att äventyrare oftare förlorar KP, och blir mer tvingade att antingen gå i grupp, hålla sig till ofarligare områden, eller ha besvärjelser och föremål som återställer KP. De kararaktärer som har få KP skulle också få lite extra nackdelar.

Idag känns det här alternativet som det mest lockande för mig (Johan), men speltestare är inte lika förtjusta.

**Comment by Itangalo** [comment]
## Om alternativ 2: ge skada vid misslyckad flykt

Det här alternativet är det som innebär minst ändringar i spelmekanismerna. Det blir mindre attraktivt att fly – det är mer eller mindre allt. De flesta simuleringar utgår från att äventyrare oftare slåss än flyr, så balansen i spelet skulle inte påverkas nämnvärt från ett sånt perspektiv.

**Comment by Itangalo** [comment]
Beta-4 sätts samman idag (2021-04-07), och då blir många flyktvärden svårare. Frågan fortsätter att utvärderas.

**Comment by Erkenberken** [comment]
En annan idé är man skulle kunna "smyga förbi"/"undvika" striden istället för fly. Som gör att man bara inte behöver slåss, men misslyckande leder då till att fienden får någon sorts fördel (+1 i strid, man får inte använda magi eller avståndsvapen, etc.) och fly är istället enklare (+1 på smyga).

**Comment by Itangalo** [comment]
> En annan idé är man skulle kunna "smyga förbi"/"undvika" striden istället för fly. Som gör att man bara inte behöver slåss, men misslyckande leder då till att fienden får någon sorts fördel (+1 i strid, man får inte använda magi eller avståndsvapen, etc.) och fly är istället enklare (+1 på smyga).

Låter som en utmärkt idé för en expansionsregel. Tack!

**Comment by Itangalo** [comment]
Första version av fiendekort med inskrivna bonusar klara. Känns som en bra approach – det blir både mer lockande att slåss och intressant att använda bonusar. Enda farhågan är att det kan ge lite för starka bonusar.

[se resultatet här](https://github.com/Itangalo/flux/files/6274611/kort.41x63.mm.kortsida.forskjuten.kopia.pdf)

**Comment by Itangalo** [comment]
Åtgärdat i beta-5. Har utvärderats litegrann och känns rätt bra. Får bli nytt ärende om det ska ändras.
