### ISSUE TITLE
Olika färg på uppdragskortens framsida?

### ISSUE THREAD

**Issue by Itangalo** [Itangalo/flux#11]
Kanske är det smart att ha färg på framsidan av uppdragskorten, och sätta färgen så att den matchar området som uppdraget utgår från. Det kan göra det lättare att identifiera korten med rätt område.

**Comment by Erkenberken** [comment]
Ja det vore bra, så man lättare hittar uppdragshögen.

**Comment by Itangalo** [comment]
Implementerat i beta-5.
