### ISSUE TITLE
Blandade stridsgrejer

### ISSUE THREAD

**Issue by Erkenberken** [Itangalo/flux#30]
Några blandade kommentarer och idéer som slagit mig/oss under speltestandet.

1. Tvåhandsvapen borde innebära att man inte kan ha en sköld. Ska man kunna ha två enhandsvapen?
2. Lågnivå vapen (+1 och oftast +2) köps/används så gott som inte då man relativt snabbt kommer upp i eller redan har +3 och det är rätt lätt att komma över ett +3 vapen. 
3. Skadereducerande utrustning (Rustning, sköld och hjälm) är sällan värt att ha då skadan sällan är ett stort problem (1-2 KP för en förlorad strid) och det inte är så många monster som gör två i skada.
4. Låt striden fortsätta tills hjälten besegrat monstret istället för att hjälten tar 1 KP i skada och så är det över. Så man kan dö på ett monster, då blir fly och smyga mer värt också.
5. Låt rustning vara ett rull 4+ så tas en skada bort oavsett om det är 1 eller 2 KP i skada, Rustning + sköld 2 x 4+

/Erik

**Comment by Itangalo** [comment]
Bra tankar. Jag har öppnat två separata issues för nr 3–5 i listan.

Angående 1: Sköldar kan inte användas tillsammans med tvåhandsvapen. (Däremot kan äventyraren bära runt på båda samtidigt.)

Angående 1, igen: Dubbla enhandsvapen tror jag skulle bli tokmäktigt. Möjligtvis kan man tänka sig att ha en besvärjelse eller nåt som låter en äventyrare tillfälligt använda två enhandsvapen, men det blir också märkligt om äventyrare ska bära runt på två enhandsvapen men bara använda dem ibland. Återkom gärna om du ser något bra sätt att få det att funka utan att saker ballar ur.

Angående 2: Bra observera. Ska fundera och öppnar förmodligen ett separat ärende för den frågan också.

**Comment by Itangalo** [comment]
Nu är #36 skapad för att ta hand om sista obehandlade frågan. Stänger den här som dublett.
