### ISSUE TITLE
Bättre ord för att "levla" sökes

### ISSUE THREAD

**Issue by Itangalo** [Itangalo/flux#35]
Att använda ordet "levla" är inte optimalt, men bästa ordet jag hittat hittills. Bättre förslag är välkomna.

**Comment by stedo880** [comment]
Ett alternativ är "förbättra förmåga **smyga**" där varje färdighet är ett keyword

**Comment by stedo880** [comment]
ELLER! "förbättra **smyga**" - plain and simple

**Comment by Itangalo** [comment]
Hm. "Förbättra" är inte så dumt ändå. Jag testar lite olika sammanhang:

* Från regler, typ: "Om du slår triss när du använder en färdighet kan du förbättra färdigheten".
* Från kort: "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen. Slå 5T6 för att försöka förbättra Smyga."
* Från karaktärsblad (svårast att få bra): "Förbättra: tre lika"
* Rubrik på referensblad: "Förbättra färdighet"
* Beskrivning på referensblad: "Vid slag där en färdighet används förbättras den man om tärningarna visar triss, och trissen är högre än nuvarande färdighetsvärde."
* Beskrivning på referensblad: "Triss på slaget för förflyttning förbättrar valfri färdighet som har lägre värde än trissen."

Jo, det funkar rätt bra. Jag funderar lite till, men jag tror att det kan bli att byta begrepp. Tack!

**Comment by Itangalo** [comment]
Letade synonymer. Det vore skönt att ha ett lite mer specifikt begrepp. "Jag levlade!" fungerar mycket bättre än "jag förbättrade!", delvis för att "levla" är så specifikt.

Några ord som känns mer eller mindre lockande: förädla, utveckla, uppgradera, vässa

Av dessa ligger not "utveckla" bäst tematiskt (eftersom karaktärerna utvecklas), medan "uppgradera" är närmast betydelsen av levla. Om man tar det ordagrant.

Söker vidare efter ord: växa, öka, stärka, mogna

Testar "utveckla" i exemplen från förra kommentaren:

- Från regler, typ: "Om du slår triss när du använder en färdighet kan du utvecklas/utveckla färdigheten".
- Från kort: "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen. Slå 5T6 för att försöka utvecklas i Smyga."
- Från karaktärsblad (svårast att få bra): "Utvecklas: tre lika"
- Rubrik på referensblad: "Utvecklas i färdigheter"
- Beskrivning på referensblad: "Vid slag där en färdighet används utvecklas den man om tärningarna visar triss, och trissen är högre än nuvarande färdighetsvärde."
- Beskrivning på referensblad: "Triss på slaget för förflyttning utvecklar valfri färdighet som har lägre värde än trissen."

Testar "stärka":

- Från regler, typ: "Om du slår triss när du använder en färdighet kan du stärka färdigheten".
- Från kort: "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen. Slå 5T6 för att försöka stärka Smyga."
- Från karaktärsblad (svårast att få bra): "Stärka: tre lika"
- Rubrik på referensblad: "Stärka färdigheter"
- Beskrivning på referensblad: "Vid slag där en färdighet används stärks den man om tärningarna visar triss, och trissen är högre än nuvarande färdighetsvärde."
- Beskrivning på referensblad: "Triss på slaget för förflyttning stärker valfri färdighet som har lägre värde än trissen."

Hm. Ska fundera mera.

**Comment by stedo880** [comment]
En variant skulle kunna vara att ha en beskrivande text, och sedan antingen "Smyga +1" eller en symbol som representerar förändringen. 

- "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen. Smyga 5T6"
- "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen." <symbol för att förbättra smyga 5T6>

Det är något som jag tycker är riktigt bra med tex Terraforming Mars, att det står i text, men när man lär sig ikonerna ser man direkt på kortet vad det kommer ge för effekt. Exempel här: https://ssimeonoff.github.io/cards-list

**Comment by Itangalo** [comment]
"Öka en färdighet". Värt att testa om det går att använda konsekvent.

Från regler, typ: "Om du slår triss när du använder en färdighet kan du öka färdigheten ett steg".
Från kort: "Du träffar broder Franz, som avgivit ett tysthetslöfte. Han ser utan att synas och går utan att höras. Han välsignar din kamp mot den Onda Trollkarlen. Slå 5T6 för att försöka öka i Smyga."
Från karaktärsblad (svårast att få bra): "Öka färdighet: tre lika"
Rubrik på referensblad: "Öka färdighet"
Beskrivning på referensblad: "Vid slag där en färdighet används ökar den om tärningarna visar triss, och trissen är högre än nuvarande färdighetsvärde."
Beskrivning på referensblad: "Triss på slaget för förflyttning ökar valfri färdighet som har lägre värde än trissen."

**Comment by Itangalo** [comment]
Nä. Levla är tydligen ett svenskt ord, så då får det vara.
